SRC = /math/src/math.c /io/src/io.c /utils/src/utils.c main.c /extra/src/extra.c


CC =  gcc

FLAGS = -o -i. 

com: SRC
	$(CC) $(FLAGS) ~/build/F $(SRC)

clean: /build/F
	rm /build/F
help: 
	@echo "I CAN NOT EVEN HELP MY SELF #_#" 
